### ISSUE TITLE
Questions about alpha of l_1 attack in CIFAR-10 exp 

### ISSUE THREAD

**Issue by Alan-Qin** [locuslab/robust_union#1]
In the code, alpha = 0.05 is used in L_1 attack . However, in the paper, the authors set alpha = 1. So should alpha by 1?

**Comment by pratyushmaini** [comment]
Since this is the top-k l_1 PGD attack, we perturb the top k directions by alpha/k at each step. For k=20, alpha=1, this turns out to be a change of 0.05 in each of the k directions. They are one and the same thing.

**Comment by Alan-Qin** [comment]
Thanks！！！！
